### ISSUE TITLE
Mobile V.1.0 - Arrow Buttons on My Current Test

### ISSUE THREAD

**Issue by lbelling** [MESH01/Mesh01App1#4]
_From @MESH02 on October 21, 2015 13:22_

In order to enter an Activity Log or upload Product Images from the My Current Tests page user needs to click the arrow button two times.

First time nothing happens. The second time it takes you to the desired page.  In general the buttons/tabs on the mobile site are not very responsive.  I feel like I have to push them multiple times before something happen.  

_Copied from original issue: MESH01/wear-test-track0#918_

**Comment by lbelling** [comment]
This is an iOS specific bug.  iOS puts a restriction on the number of instructions within a loop, and our app exceeds this (though probably doesn't need to if better tuned).
I have a TC contest ready to go, as soon as they turn our account back on.

**Comment by manishsinghbisht** [comment]
By instructions, does it mean server calls?


Regards,
Manish

-------- Original Message --------

**Comment by lbelling** [comment]
No, it's within the iOS app, not related to server calls.

**Comment by manishsinghbisht** [comment]
Ok, I will study it.


Regards,
Manish

-------- Original Message --------

**Comment by lbelling** [comment]
This turned out to be a bug in Angular.  They put out a patch for it, which fixed the problem.
